### ISSUE TITLE
Ground truth for the demo data

### ISSUE THREAD

**Issue by dow980** [michael-fonder/fonder_thesis-2016#1]
Hi Michael,
Thanks a lot for sharing your code. I am wondering if the ground truth data is included in the data.yml file or not. BTW, have you ever tested your code using some other public test data, such as EuRoC Mav dataset (http://projects.asl.ethz.ch/datasets/doku.php?id=kmavvisualinertialdatasets)?
Thanks

**Comment by michael-fonder** [comment]
Hi Thomas,
I'm glad to see that my work may help someone. 
To answer your questions, yes, the data.yml file generated by the simulator includes the interesting ground truth information (the position relative to the starting point and the attitude of the body in quaternion).
And, no, due to several delays encountered during the implementation of the filter, I did not have enough time to test the whole code on a public dataset. Also, I did this work in partnership with a company, so I prioritized experimental tests made with their own platform. If you want a complete and detailed overview of what was made and tested, I encourage you to request a copy of my report at the following URL (it free but you have to request it) : http://hdl.handle.net/2268.2/1523 (I updated the main readme with this information).
I hope it answers your questions.

**Comment by meyiao** [comment]
Hi Michael, 
Really appreciate that you share the code! 
My request for a copy of your report was refused. Could you please email me a copy?
Email address: jinaqiaoqiao@gmail.com
Thanks a lot!!!

**Comment by michael-fonder** [comment]
Hi meyiao,
It appears that the full text can not be distributed as such due to some confidential information given about the partner company (I was unaware of that). In the next days, I will upload a version where all those information are hidden or removed without hurting the core content of my work and which can be freely accessed by everyone. I will post an update on this thread when it will be done.

**Comment by supitalp** [comment]
Hi Michael,
Any news regarding a safe copy of your work? I would be quite interested!

Thanks,
supitalp
